<?php

include_once('../_globals/functions.inc.php');


$nav_section = 'work';

$page_title = 'thesa.me - Greg Leuch: Creative + User Interaction';


?>
<!DOCTYPE html>
<html>
<?php include '../_globals/template_header.inc.php'; ?>
<body class="client work_item">
 <div id="template_wrapper" class="c">
  <div class="rel c">

   <article id="content" class="work_item">

    <?php include_once('../_globals/flash.inc.php') ?>

    <div class="item_intro rel">
     <section class="intro">
      <h4>Design, Identity</h4>
      <h1>thesa.me</h1>
      <p class="large serif">An online web application manager and distributive content publisher.</p>
     </section>

     <section class="featured_images rel">
      <div class="carousel">
       <!-- TODO FIGURE OUT LATER -->
      </div>
      <div class="carousel_buttons">
       <a href="javascript:;" class="prev"><i class="icon prev">Previous</i></a>
       <a href="javascript:;" class="next"><i class="icon next">Next</i></a>
      </div>
     </section>
    </div>

    <section class="about paragraph c">
     <h3>About</h3>
     <p class="medium serif">Thesa.me is a online web application organizer and distributive content publisher marketed as a substitution for their social browsing. This new resource aims to create an online application that aggregates and filters information from other web sites within a central dashboard interface and feed-based pages. Information will be taken from social-based web sites, including Facebook, Twitter, WordPress blogs, and Tumblr. thesa.me will also allow a user to distribute content across multiple web apps by synchronizing information into relevant content categories, including status updates, articles, links, photos, videos, quotes, and audio clips.</p>
     <p class="medium serif">The true purpose of thesa.me is to further explore data portability among web sites. By providing users with the ability to condense and filter their web apps into one web site, thesa.me will give them a unique experience with content they may miss, allowing them to discover new dialogue, organize their apps, and connect with their friends/followers through other network.</p>
    </section>

    <section class="challenge paragraph c">
     <h3>Challenge</h3>
     <p class="medium serif">As the final project for completion of my degree in Graphic Design from Auburn University, I took to the task of creating an internet startup company that aims to showcase a possible proof-of-concept for an online web application manager and distributive content publisher. This required creatives ways to explaining the reasons for collecting content from other web applications (such as Facebook & Twitter), while describing the methods that allow the simultaneous publication of different web content across multiple web mediums.</p>
    </section>

    <section class="solution paragraph c">
     <h3>Solution</h3>
     <p class="medium serif">I employed the use of shape, pattern, and line to convey different marketing messages, while keeping a clean, off-beat aesthetic to build interest and a unique brand identity. This project took a unique shape by gathering input from potential users, including those with little experience in social media.</p>
    </section>

    <section class="result paragraph c">
     <h3>Result</h3>
     <p class="medium serif">A lot of buzz was generated by the final project, with many desiring to use such a unique web app to manage online identities. The final pieces created a harmonious array of work, including a beautiful identity and brilliant web interface designs, combined with a straight-forward demonstration slideshow and different marketing pieces.</p>
    </section>

    <?php include '../_globals/work.footer.inc.php'; ?>

   </article>

   <aside id="sidebar">
    <section class="box">
     <h4>Tasks</h4>
     <p>brainstorm, design, research</p>
     <h4>Client</h4>
     <p>Undergraduate Senior Thesis</p>
     <h4>Finished</h4>
     <p>Nov 2008</p>
     <p>&nbsp;<br /><a target="_blank" href="http://vimeo.com/2230920">Demo Video</a></p>
    </section>
   </aside>
  </div>

<?php include '../_globals/header.inc.php'; ?>

 </div>

 <div id="template_static_bar"></div>

<?php include '../_globals/footer.inc.php'; ?>


</body>
</html>